### ISSUE TITLE
EDA train set y modelo Baseline

### ISSUE THREAD

**Issue by mateoarv** [mateoarv/kaggle-elo#3]
* Análisis exploratorio del train set
* Construcción de un modelo baseline

**Comment by gitierrez** [comment]
Análisis exploratorio de `train.csv` completo.

Se propone para futuros análisis la utilización de GDS para visualización rápida, recientemente integrada con Kaggle:

http://blog.kaggle.com/2018/12/05/announcing-kaggle-integration-with-google-data-studio/

**Comment by gitierrez** [comment]
Modelo baseline con alrededor de 200.000 registros está tardando mucho para modelos sencillos. Especificaciones:

* Entrenamiento en paralelo en 4 CPU
* 201.917 observaciones
* 8 features (1 numérica, 7 categóricas)
* Pipeline de transformación: Transformación de fechas -> OHE -> Scaling
* 3 modelos: Elastic Net, Support Vector Machine, Random Forest
* Ajuste de hiperparámetros con Randomized Grid Search, 10 evaluaciones, 5-fold CV.
* Métrica de error: RMSE

Resultados: (%f; %f) % (training_time (minutos), score_on_test_set (RMSE))
* Elastic net: (1.8; 3.595)
* SVM: (1005.9; 3.606)
* RF: (64.6; 3.592)

Conclusiones:
* La inclusión de los demás datasets, ya sea por agregación (incremento de features) o por recurrencia (tensorización en el tiempo), demandará muchos recursos computacionales (especialmente con modelos más sofisticados y más iteraciones/folds de Random Grid Search/Cross Validation).
* Arquitecturas computacionales posibles:
    * Standalone con CUDA - limitarnos a modelos altamente paralelizables y de relativamente baja complejidad computacional (modelos con complejidad >= O(n^3) sin distribución de datos se vuelven inmanejables). Adicionalmente tendríamos que estimar cuánta RAM necesitan los modelos, asumo que 32GB son suficientes, pero depende de los modelos y las implementaciones que utilicemos.
    * Cluster de Hadoop con Spark - un poco más difícil de implementar, pero puede ser más eficiente. Integración Spark-Keras con Elephas @ https://github.com/maxpumperla/elephas
* Random Forest tuvo el mejor resultado, pero no por mucho con respecto al Elastic Net. Se conjetura que la dificultad está en obtener mejores predictores y fuertes regularizaciones, y no tanto en la geometría del problema, pues Random Forest tiene una geometría mucho más flexible que Elastic Net y aún así sus RMSE son similares.
